% This code concatenates sampled wave files produced during a simulation into one wave file.
% Megan K. Finnegan & Anne S. Warlaumont

smplint = 300; % Sampling interval. i.e. How many .wav files to skip.
totalsec = 7200; % Total number of seconds of simulation time to include in the concatenated sound file.
skipmissing = 0;

% Names/ID Numbers of simulations, separated on reinforcement type. All
% yoked controls MUST be placed in the "_yoke" sim types!
simnames = {...
            'NandScExtended_2_1_1',...
            'NandScExtended_2_1_1',...
            'NandScExtended_2_1_2',...
            'NandScExtended_2_1_2',...
            'NandScExtended_2_1_3',...
            'NandScExtended_2_1_3',...
            'NandScExtended_2_1_4',...
            'NandScExtended_2_1_4',...
            'NandScExtended_2_1_5',...
            'NandScExtended_2_1_5',...
            'NandScExtended_2_2_1',...
            'NandScExtended_2_2_2',...
            'NandScExtended_2_2_3',...
            'NandScExtended_2_2_4',...
            'NandScExtended_2_2_5',...
            'NandScTesting_3_1_1',...
            'NandScTesting_3_1_2',...
            'NandScTesting_3_1_3',...
            'NandScTesting_3_1_4',...
            'NandScTesting_3_1_5',...
            'NandScTesting_3_2_1',...
            'NandScTesting_3_2_2',...
            'NandScTesting_3_2_3',...
            'NandScTesting_3_2_4',...
            'NandScTesting_3_2_5',...
            'NandScTesting_3_3_1',...
            'NandScTesting_3_3_2',...
            'NandScTesting_3_3_3',...
            'NandScTesting_3_3_4',...
            'NandScTesting_3_3_5',...
            'NandScTesting_2_1_1',...
            'NandScTesting_2_1_2',...
            'NandScTesting_2_1_3',...
            'NandScTesting_2_1_4',...
            'NandScTesting_2_1_5',...
            'NandScTesting_2_2_1',...
            'NandScTesting_2_2_2',...
            'NandScTesting_2_2_3',...
            'NandScTesting_2_2_4',...
            'NandScTesting_2_2_5',...
            'NandScTesting_2_3_1',...
            'NandScTesting_2_3_2',...
            'NandScTesting_2_3_3',...
            'NandScTesting_2_3_4',...
            'NandScTesting_2_3_5',...
            'NandScTesting_1_1_1',...
            'NandScTesting_1_1_2',...
            'NandScTesting_1_1_3',...
            'NandScTesting_1_1_4',...
            'NandScTesting_1_1_5',...
            'NandScTesting_1_2_1',...
            'NandScTesting_1_2_2',...
            'NandScTesting_1_2_3',...
            'NandScTesting_1_2_4',...
            'NandScTesting_1_2_5',...
            'NandScTesting_1_3_1',...
            'NandScTesting_1_3_2',...
            'NandScTesting_1_3_3',...
            'NandScTesting_1_3_4',...
            'NandScTesting_1_3_5',...
            'NandScExtended_1_2_1',...
            'NandScExtended_1_2_2',...
            'NandScExtended_1_2_3',...
            'NandScExtended_1_2_4',...
            'NandScExtended_1_2_5',...
            'NandScExtended_1_3_1',...
            'NandScExtended_1_3_2',...
            'NandScExtended_1_3_3',...
            'NandScExtended_1_3_4',...
            'NandScExtended_1_3_5',...
            }
simwavpaths = {...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_2_1_1_Wave/',...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_2_1_1_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_2_1_2_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_2_1_2_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_2_1_3_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_2_1_3_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_2_1_4_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_2_1_4_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_2_1_5_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_2_1_5_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_2_2_1_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_2_2_2_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_2_2_3_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_2_2_4_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_2_2_5_Wave/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_3_1_1/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_3_1_2/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_3_1_3/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_3_1_4/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_3_1_5/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_3_2_1/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_3_2_2/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_3_2_3/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_3_2_4/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_3_2_5/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_3_3_1/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_3_3_2/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_3_3_3/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_3_3_4/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_3_3_5/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Subset_Sims_Parameters_Used_In_Human_Trials/NandScTesting_Wave_2_1_1/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Subset_Sims_Parameters_Used_In_Human_Trials/NandScTesting_Wave_2_1_2/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Subset_Sims_Parameters_Used_In_Human_Trials/NandScTesting_Wave_2_1_3/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Subset_Sims_Parameters_Used_In_Human_Trials/NandScTesting_Wave_2_1_4/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Subset_Sims_Parameters_Used_In_Human_Trials/NandScTesting_Wave_2_1_5/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Subset_Parameters_with_Next_Best_Performance/NandScTesting_Wave_2_2_1/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Subset_Parameters_with_Next_Best_Performance/NandScTesting_Wave_2_2_2/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Subset_Parameters_with_Next_Best_Performance/NandScTesting_Wave_2_2_3/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Subset_Parameters_with_Next_Best_Performance/NandScTesting_Wave_2_2_4/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Subset_Parameters_with_Next_Best_Performance/NandScTesting_Wave_2_2_5/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_2_3_1/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_2_3_2/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_2_3_3/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_2_3_4/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_2_3_5/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_1_1_1/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_1_1_2/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_1_1_3/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_1_1_4/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_1_1_5/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_1_2_1/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_1_2_2/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_1_2_3/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_1_2_4/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_1_2_5/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_1_3_1/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_1_3_2/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_1_3_3/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_1_3_4/' ...
               '/chroot/lab/BabbleNN/Neuron_and_MuscleScaling_Tests/Rest_of_Neuron_and_Muscscale_Tests/NandScTesting_Wave_1_3_5/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_1_2_1_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_1_2_2_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_1_2_3_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_1_2_4_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_1_2_5_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_1_3_1_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_1_3_2_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_1_3_3_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_1_3_4_Wave/' ...
               '/chroot/lab/BabbleNN/Extended_Neuron_and_Scaling_Tests/NandScExtended_1_3_5_Wave/' ...
               };
newsoundfiles = {...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_2m_sim1.wav',...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_2m_sim1_yoked.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_2m_sim2.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_2m_sim2_yoked.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_2m_sim3.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_2m_sim3_yoked.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_2m_sim4.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_2m_sim4_yoked.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_2m_sim5.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_2m_sim5_yoked.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_3m_sim1.wav',...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_3m_sim2.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_3m_sim3.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_3m_sim4.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_3m_sim5.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_4m_sim1.wav',...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_4m_sim2.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_4m_sim3.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_4m_sim4.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_4m_sim5.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_5m_sim1.wav',...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_5m_sim2.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_5m_sim3.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_5m_sim4.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_5m_sim5.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_6m_sim1.wav',...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_6m_sim2.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_6m_sim3.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_6m_sim4.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_200n_6m_sim5.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_100n_4m_sim1.wav',...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_100n_4m_sim2.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_100n_4m_sim3.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_100n_4m_sim4.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_100n_4m_sim5.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_100n_5m_sim1.wav',...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_100n_5m_sim2.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_100n_5m_sim3.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_100n_5m_sim4.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_100n_5m_sim5.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_100n_6m_sim1.wav',...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_100n_6m_sim2.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_100n_6m_sim3.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_100n_6m_sim4.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_100n_6m_sim5.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_4m_sim1.wav',...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_4m_sim2.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_4m_sim3.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_4m_sim4.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_4m_sim5.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_5m_sim1.wav',...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_5m_sim2.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_5m_sim3.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_5m_sim4.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_5m_sim5.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_6m_sim1.wav',...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_6m_sim2.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_6m_sim3.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_6m_sim4.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_6m_sim5.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_7m_sim1.wav',...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_7m_sim2.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_7m_sim3.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_7m_sim4.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_7m_sim5.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_8m_sim1.wav',...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_8m_sim2.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_8m_sim3.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_8m_sim4.wav' ...
                 '/chroot/lab/BabbleNN/SoundsOverTime/SoundsOverTime_50n_8m_sim5.wav' ...
                 };

% Keeps track of whether the simulation type is a yoked control or not.
% Needed to specify the right workspace filename.
isityoked = [...
0,1,0,1,0,1,0,1,0,1,...
0,0,0,0,0,...
0,0,0,0,0,...
0,0,0,0,0,...
0,0,0,0,0,...
0,0,0,0,0,...
0,0,0,0,0,...
0,0,0,0,0,...
0,0,0,0,0,...
0,0,0,0,0,...
0,0,0,0,0,...
0,0,0,0,0,...
0,0,0,0,0];

% Making reservoir songs.
for trial=1:length(simwavpaths) % Looking at every simulation
        
        if(isityoked(trial))
            wavfilebase = strcat(simwavpaths{trial},'synth_', simnames{trial}, '_yoke');
        else
            wavfilebase = strcat(simwavpaths{trial},'synth_', simnames{trial});
        end
        
        % Making the reservoir .wav file
		mstrwav=[];
        for currSec = 1:smplint:totalsec % Looping through all the wave files I want to concatenate.
            if verLessThan('matlab', '8.1.0') % This if-statement is for backward compatibility. wavread is being phased out, but older versions of MATLAB use it.
                [nxtwav, fs, bits] = wavread(strcat(wavfilebase, '_', num2str(currSec), '.wav'));
            else
				display(strcat(wavfilebase, '_', num2str(currSec), '.wav'));
                [nxtwav, fs] = audioread(strcat(wavfilebase, '_', num2str(currSec), '.wav'));
            end
			mstrwav = [mstrwav; nxtwav];
        end
        
        % Writing the master wave file.
        if verLessThan('matlab', '8.1.0')
            wavwrite(mstrwav, fs, bits, newsoundfiles{trial});
        else
            audiowrite(newsoundfiles{trial}, mstrwav, fs);
        end
end
